name: submit-ios

on:
  workflow_dispatch:

jobs:
  build_ios_production:
    name: Build iOS production
    type: build
    params:
      platform: ios
      profile: production
  submit_ios_testflight:
    name: Submit iOS to TestFlight
    needs: [build_ios_production]
    type: testflight
    params:
      build_id: ${{ needs.build_ios_production.outputs.build_id }}
